added loader in spends view, and in login view
akaDuality/Niffler pull request #2
Opened 2023-11-29 14:13 UTC by Xanuriknur

2023-11-29 14:40 UTC, akaDuality requested changes

2023-11-29 14:40 UTC, akaDuality commented on Niffler/Niffler/NifflerApp.swift
> +                isRegistrationPresented: $isRegistrationPresented,
Чет вот тут странно, что регистрация внутрь трат ушла. Мне кажется, это прям не нужно, потому что экран у тебя может в итоге на этом месте быть другой и авторизация должна появляться именно относительно всего приложения

2023-11-29 15:23 UTC, Xanuriknur commented on Niffler/Niffler/NifflerApp.swift
> +                isRegistrationPresented: $isRegistrationPresented,
пробую через переменные окружения Типо:

```
struct MyEnvironmentKey: EnvironmentKey {
    static var defaultValue: String = "Default Value"
}

extension EnvironmentValues {
    var myCustomValue: String {
        get { self[MyEnvironmentKey.self] }
        set { self[MyEnvironmentKey.self] = newValue }
    }
}

struct ContentView: View {
    @Environment(\.myCustomValue) private var customValue
```
или
```
class UserData: ObservableObject {
    @Published var username = "JohnDoe"
}


struct ContentView: View {
    @EnvironmentObject var userData: UserData
    
    var body: some View {
        Text("Username: \(userData.username)")
            .onTapGesture {
                userData.username = "NewUser"
            }
    }
}

```
или

2023-11-29 15:24 UTC, Xanuriknur commented on Niffler/Niffler/NifflerApp.swift
> +                isRegistrationPresented: $isRegistrationPresented,
смотрю насколько это будет работать так же как @State'

2023-12-02 11:42 UTC, Xanuriknur commented on Niffler/Niffler/NifflerApp.swift
> +                isRegistrationPresented: $isRegistrationPresented,
Унес логкиу в кнопку logout, и вытащали ее из spends

2023-12-03 11:45 UTC, akaDuality approved these changes

2023-12-03 11:45 UTC, akaDuality commented on Niffler/Niffler/VIew/LoginView.swift
> +                isLoginSuccessful = true
Вот это условие уже можно удалить, заполненные поля могут валидировать форму, но точно не заканчивают сценарий

2023-12-03 11:45 UTC, akaDuality commented on Niffler/Niffler/NifflerApp.swift
> +                    .frame(width: geometry.size.width * 0.8)
Кажется, что неправильно, что кнопка решает какой у нее будет размер. Лучше, чтобы geomertyReader был уровнем выше, около WindowGroup

2023-12-04 05:06 UTC, Xanuriknur commented on Niffler/Niffler/NifflerApp.swift
> +                    .frame(width: geometry.size.width * 0.8)
унес на уровень WindowGroup

2023-12-04 05:10 UTC, Xanuriknur commented on Niffler/Niffler/VIew/LoginView.swift
> +                isLoginSuccessful = true
удалив

2023-12-04 05:10 UTC, merged