First UI test
akaDuality/Niffler pull request #3
Opened 2023-12-07 08:30 UTC by Xanuriknur

2023-12-07 15:57 UTC, akaDuality requested changes

2023-12-07 15:57 UTC, akaDuality commented on Niffler/Api/Sources/Api/Spends.swift
> +    public func toDictionary() -> [String: Any] {
Сейчас делают иначе:
```
struct SpendDto: Encodable {
   id: String
   spendDate: Date
   ...
}

let data = try JsonEncoder().encode(SpendDto(id: ...))
```

2023-12-07 15:57 UTC, akaDuality commented on Niffler/Api/Sources/Api/UserDefaultsWrapper.swift
> +public class UserDefaultsWrapper: UserDefaultsWrapperProtocol {
А что поменялось от вропера?

2023-12-08 10:57 UTC, Xanuriknur commented on Niffler/Api/Sources/Api/Spends.swift
> +    public func toDictionary() -> [String: Any] {
точно! face palm

2023-12-08 10:57 UTC, Xanuriknur commented on Niffler/Api/Sources/Api/UserDefaultsWrapper.swift
> +public class UserDefaultsWrapper: UserDefaultsWrapperProtocol {
если честно, хотелось красивое - но это сахар
удалю

2023-12-08 14:22 UTC, akaDuality commented on Niffler/Api/Sources/Api/UserDefaultsWrapper.swift
> +public class UserDefaultsWrapper: UserDefaultsWrapperProtocol {
Надо задачу понимать просто, я пока не понимаю. 

Если мы хотим отделить для тестов, то это решается тем, что сам UserDefault надо брать не standart, а передавать его в конструктор. Тогда в тестах его можно будет подменить и все заработает. 

Если тебе нужно какое-то абстрактное хранилище, т.е. ты планируешь переделать на keychain, например, то ок, это решение подходит. Но протокол тогда надо назвать как-то иначе и тудушка написать, что вот этот протокол в будущем вот для этого. Или в документации к методу. 

Могу потом показать оба варианта в живую

2023-12-26 12:22 UTC, akaDuality requested changes

2023-12-26 12:22 UTC, akaDuality commented on Niffler/Api/Sources/Api/Helpers/DateFormatterHelper.swift
> +        return formatter.string(from: dateForm)
Вынести в проперти, потому что форматтер медленно создается

2023-12-26 12:22 UTC, akaDuality commented on Niffler/Api/Sources/Api/Network.swift
> +    }
На encodable можно сделать

2023-12-26 12:22 UTC, akaDuality commented on Niffler/Api/Sources/Api/Network.swift
> +public class Network: ObservableObject {
Добавить комментарий, что это для того, чтобы прокидывать его как environmentObject

2023-12-26 12:22 UTC, akaDuality commented on Niffler/Api/Sources/Api/Spends.swift
> +}
Убрать тут

2023-12-26 12:22 UTC, akaDuality commented on Niffler/Niffler/VIew/AddSpendView.swift
> +// }
Восстановить

2023-12-27 06:39 UTC, Xanuriknur commented on Niffler/Niffler/VIew/AddSpendView.swift
> +// }
Восстановил, можно юзать .constant для Binding

2023-12-27 06:41 UTC, Xanuriknur commented on Niffler/Api/Sources/Api/Network.swift
> +public class Network: ObservableObject {
добавил

2023-12-27 09:16 UTC, akaDuality approved these changes

2023-12-27 09:16 UTC, merged